Added Sqrt() for Fraction
danm-de/Fractions pull request #13
Opened 2022-02-17 14:36 UTC by MadsKirkFoged

This is my attempt to create the sqrt() function for Fractions.

I hope it is okay that I have created it as an Extension Method, I like this:
`Fraction.One.Sqrt()`
over 
`Fraction.Sqrt(Fraction.One)`

I have never used FluentAssertions test system, but I hope what I have created will work for you.

What do you think?

2022-02-17 18:33 UTC, danm-de commented
Hey, thanks. 
I will take a closer look at it over the weekend

2022-02-20 11:24 UTC, MadsKirkFoged commented
Just added a way for users to set their desired accuracy

2022-02-20 14:04 UTC, danm-de requested changes

2022-02-20 14:04 UTC, danm-de commented on tests/Fractions.Tests/FractionSpecs/Sqrt/Method_Sqrt.cs
> +
Yeah, the tests... *Fractions* started as private project. Nearly every single line was written in German language 🥲. I am sorry for not writing proper tests in the first place. However, the use of TestCases makes more verbose tests:

![image](https://user-images.githubusercontent.com/3825484/154846261-dcba18b9-14ba-42af-a9d4-5b8245118869.png)

**CAUTION** SUGGESTION REQUIRES A NEW USING `using System.Collections.Generic;` 

```suggestion
        private static IEnumerable<TestCaseData> TestCases {
            get {
                yield return new TestCaseData(0.001);
                yield return new TestCaseData(5);
                yield return new TestCaseData(4.54854751);
                yield return new TestCaseData(9999999855487);
                yield return new TestCaseData(99999998554865557);
                yield return new TestCaseData(Math.PI);
            }
        }

        [Test,TestCaseSource(nameof(TestCases))]
        public void Should_the_result_be_equal_to_Math_Sqrt(double value) {
            var expected = Math.Sqrt(value);
            var actual = Fraction.FromDouble(value).Sqrt();
            actual.ToDouble().Should().Be(expected);
        }```

2022-02-20 15:58 UTC, MadsKirkFoged commented on src/Fractions/Fraction.Extensions.cs
> +            var guessDouble = Math.Sqrt((double)x);
I tested it - It cant overflow, it just set the double to INF which we then checks for

2022-02-20 16:09 UTC, MadsKirkFoged commented
I think I have fixed your request! Let me know if I missed something or you find something else!

2022-02-20 16:35 UTC, merged